#
# index of all available themes in this gallery
#
# this file allows tomcat-manager to only fetch one
# file and be able to show all information about all
# themes in this gallery
#

[monokai]
file="monokai.toml"
description="monokai theme using color scheme from https://monokai.pro/"

[solarized-dark]
file="solarized-dark.toml"
description="dark theme using solarized color scheme from https://ethanschoonover.com/solarized/"

[solarized-light]
file="solarized-light.toml"
description="light theme using solarized color scheme from https://ethanschoonover.com/solarized/"
